# Conexión principal a Oracle 21c
# Reemplaza XE o PDB1 dependiendo del nombre de tu base de datos local
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1 
spring.datasource.username=Daniel
spring.datasource.password=Fifa27**
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate / JPA (Convierte el código Java a Oracle dialect)
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
