server.port=9090
spring.application.name=hospital

# Clave secreta para JWT (puedes cambiar este texto por cualquier cadena larga)
jwt.secret=mi_clave_secreta_super_segura_para_el_hospital_123456789

# Configuración de H2 para que guarde los datos en un archivo local (opcional)
spring.datasource.url=jdbc:h2:mem:hospitaldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Esto permite que Spring cree las tablas automáticamente basándose en tus clases @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
